import type { Metadata } from "next";
import NavBar from "./components/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "HNG_TICKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-[radial-gradient(ellipse_at_bottom,_#0E464F_-10%,_#02191D_40%)] min-h-screen relative px-2"
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
